drfsite/drfsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .yasg import urlpatterns as doc_urls


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('sport/', include('sport.urls', namespace="sport")),
    path('users/', include('users.urls', namespace="users")),
    # path('api/v1/drf-auth/', include('rest_framework.urls')),

    # path('api/v1/clubs/', ClubsAPIList.as_view(), name='clubs-list'),
    # path('api/v1/clubs/<int:pk>/', ClubsAPIUpdate.as_view(), name='clubs-update'),
    # path('api/v1/clubs/<int:pk>/delete/', ClubsAPIDestroy.as_view(), name='clubs-delete'),
    # path('api/v1/sportlist/', SportTypesAPIView.as_view()),
    # path('api/v1/sportlist/<int:pk>/', SportTypesAPIView.as_view()),
    # path('api/v1/clubs/', ClubsAPIList.as_view()),
    # path('api/v1/clubs/<int:pk>/', ClubsAPIUpdate.as_view()),
    # path('api/v1/clubdetail/<int:pk>/', ClubsAPIDetailView.as_view()),
    # path('api/v1/clubs/', ClubsViewSet.as_view({'get': 'list', 'post': 'create'})),
    # path('api/v1/clubs/<int:pk>/', ClubsViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),

    path('', RedirectView.as_view(url='/sport/', permanent=True)),
]

urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

drfsite/sport/urls.py
from .views import *
from django.urls import path, include, re_path
from rest_framework import routers
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = "sport"

router = routers.SimpleRouter()
router.register(r'sports', SportTypesViewSet, basename='sports')
router.register(r'category', CategoryViewSet, basename='category')
router.register(r'clubs', ClubsViewSet, basename='clubs')
router.register(r'veterans', VeteransViewSet, basename='veterans')


urlpatterns = [
    path('api/v1/', include(router.urls)),
    # path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),


]

drfsite/users/urls.py
from .views import *
from django.urls import path, include, re_path
from rest_framework import routers
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = "users"

router = routers.SimpleRouter()
router.register(r'users', UsersTypesViewSet, basename='users')

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('api/v1/register/', RegisterView.as_view(), name='register'),
    path('api/v1/login/', LoginAPIView.as_view(), name='login'),
    path('api/v1/logout/', LogoutAPIView.as_view(), name='logout'),
    path('api/v1/profile/', Profile.as_view(), name='profile'),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

drfsite/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """ Таблица Пользователи """
    username = models.CharField(max_length=255, unique=True, verbose_name="Логин")
    password = models.CharField(max_length=255, unique=False, verbose_name="Пароль")
    last_login = models.DateTimeField(auto_now=True, verbose_name="Последнее время вхождения")
    is_superuser = models.BooleanField(default=False, verbose_name="Superuser")
    email = models.EmailField(max_length=255, unique=True, verbose_name="Email")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Аватарка")
    is_active = models.BooleanField(default=True, verbose_name="Active")
    is_staff = models.BooleanField(default=False, verbose_name="Staff")
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    first_name = models.CharField(max_length=255, blank=True, verbose_name="Имя")
    last_name = models.CharField(max_length=255, blank=True, verbose_name="Фамилия")
    date_birth = models.DateField(blank=True, null=True, verbose_name="Дата рождения")

    def __str__(self):
        return self.username

drfsite/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm

from .models import *


class LoginUserForm(AuthenticationForm):
    """ Форма авторизации """
    username = forms.CharField(max_length=100,
                               label_suffix="",
                               label="Логин",
                               widget=(
                                   forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Логин или E-mail'})))
    password = forms.CharField(label_suffix="",
                               label="Пароль",
                               widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Пароль'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    """ Форма регистрации """
    email = forms.EmailField(
        required=True, label_suffix="", label="Email",
        error_messages={'invalid': ''}
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if CustomUser.objects.filter(username=username).exists():  # __iexact - воспринимает любой регистр за один
            raise forms.ValidationError("Такой Логин уже существует!")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают")
        return password2


class UpdateProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               disabled=True,
                               widget=(
                                   forms.TextInput(attrs={'class': 'form-input'})))
    email = forms.CharField(label='Email',
                            disabled=True,
                            widget=(
                                forms.TextInput(attrs={'class': 'form-input'})))

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'photo', 'date_birth']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class CustomPasswordRestForm(PasswordResetForm):
    """ Форма сброса пароля """

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь не найден')
        return email

drfsite/users/views.py
from django.contrib.auth import authenticate
from django.forms import model_to_dict
from django.shortcuts import render
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from pyexpat.errors import messages
from .models import *

# DRF
from rest_framework import generics, status
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter
from rest_framework.decorators import action
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework import viewsets
from .serializers import *


class ClubsAPIListPagination(PageNumberPagination):
    page_size = 3
    page_size_query_param = 'page_size'
    max_page_size = 10000


class SingleObjectMixin:
    # pagination_class = ClubsAPIListPagination
    filter_backends = [DjangoFilterBackend, OrderingFilter, filters.SearchFilter]

    def get_queryset(self):
        pk = self.kwargs.get("pk")
        if not pk:
            return self.queryset.all()
        return self.queryset.filter(pk=pk)


class RegisterView(APIView):
    """ Регистрация """
    def post(self, request):
        serializer = UsersTypesSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            refresh = RefreshToken.for_user(user) # Создание Refesh и Access
            refresh.payload.update({    # Полезная информация в самом токене
                'user_id': user.id,
                'username': user.username
            })
            return Response({
                'refresh': str(refresh),
                'access': str(refresh.access_token), # Отправка на клиент

            }, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LoginAPIView(APIView):
    """ Авторизация """
    def post(self, request):
        username = request.data.get('username', None)
        password = request.data.get('password', None)
        if username is None or password is None:
            return Response({'error': 'Требуется указать имя пользователя и пароль'},
                            status=status.HTTP_400_BAD_REQUEST)
        user = authenticate(request, username=username, password=password)
        if user is None:
            return Response({'error': 'Неверные данные'},
                            status=status.HTTP_401_UNAUTHORIZED)
        refresh = RefreshToken.for_user(user)
        refresh.payload.update({
            'user_id': user.id,
            'username': user.username
        })
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token),
        }, status=status.HTTP_200_OK)


class LogoutAPIView(APIView):
    """ Выход из системы """
    def post(self, request):
        refresh_token = request.data.get('refresh_token') # С клиента нужно отправить refresh token
        if not refresh_token:
            return Response({'error': 'Необходим Refresh token'},
                            status=status.HTTP_400_BAD_REQUEST)
        try:
            token = RefreshToken(refresh_token)
            token.blacklist() # Добавить его в чёрный список
        except Exception as e:
            return Response({'error': 'Неверный Refresh token'},
                            status=status.HTTP_400_BAD_REQUEST)
        return Response({'success': 'Выход успешен'}, status=status.HTTP_200_OK)


class Profile(APIView):
    """ Профиль """
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        serializer = UsersTypesSerializer(request.user)
        return Response(serializer.data)

    def put(self, request, *args, **kwargs):
        user = request.user

        # Создаем сериализатор для обновления данных
        serializer = UsersTypesSerializer(user, data=request.data, partial=True)

        if serializer.is_valid():
            # Сохраняем изменения
            serializer.save()

            # Если передан новый пароль, хешируем его
            if 'password' in request.data:
                user.set_password(request.data['password'])
                user.save()

            # Возвращаем обновленные данные пользователя
            return Response(serializer.data, status=status.HTTP_200_OK)

        # Возвращаем ошибки валидации
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UsersTypesViewSet(SingleObjectMixin, viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UsersTypesSerializer
    filterset_fields = ['username', ]
    ordering_fields = ['username',]
    search_fields = ['username']

drfsite/users/templates/users/acc_active_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f6f9fc;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #0072ff;
        }
        p {
            font-size: 16px;
            line-height: 1.5;
            color: #333;
        }
        a.button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            background-color: #0072ff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            text-align: center;
        }
        a.button:hover {
            background-color: #005bb5;
        }
        footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Здравствуйте, {{ user.username }}!</h1>
        <p>Для активации вашего аккаунта на сайте <strong>{{ domain }}</strong> нажмите на ссылку ниже:</p>
        <a class="button" href="http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}">Активировать аккаунт</a>
        <p>Спасибо!</p>
    </div>
    <footer>
        <p>&copy; {{ current_year }} {{ domain }}. Все права защищены.</p>
    </footer>
</body>
</html>

drfsite/users/templates/users/activation_invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/active_email.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Недействительная активация</title>
</head>
<body>
    <div class="container">
        <h2>Недействительная активация</h2>
        <p>Ссылка для активации недействительна или истекла. Пожалуйста, попробуйте зарегистрироваться снова.</p>
        <p><a href="{% url 'users:register' %}">Зарегистрироваться</a></p>
    </div>
</body>
</html>

drfsite/users/templates/users/email_confirmation_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/active_email.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Подтверждение регистрации</title>
</head>
<body>
    <div class="container">
        <h2>Подтверждение регистрации</h2>
        <p>Ссылка для подтверждения регистрации была отправлена на вашу почту
            <a href="mailto:{{ user.email }}">{{ user.email }}</a>.
            Проверьте ваш email для активации аккаунта.
        </p>
    </div>
</body>
</html>

drfsite/users/templates/users/feedback_email_send.html
{% autoescape off %}

Здравствуйте, Администратор,

С контактной формы поступило новое сообщение со следующим содержимым:

    {{ content }}

    IP Адрес отправителя: {{ ip }}
    Email отправителя: {{ email }}
    {% if user %}Пользователь: {{ user.username }}{% endif %}


{% endautoescape %}

drfsite/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/login.css' %}">
{% endblock %}

{% block toppanel %}
{% endblock %}

{% block content %}

<div class="login-form">
    <h2 style="text-align: center; margin-bottom: 20px;">Авторизация</h2>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        <input type="hidden" name="next" value="{{ next }}" />
        <p><button type="submit">Войти</button></p>
        <small class="form-group">
             <div class="form-check form-switch">
                <label class="form-check-label" for="rememberMe">Запомнить меня
                    <input class="form-check-input" id="rememberMe" type="checkbox" name="rememberMe"/>
                </label>
                <div class="spacer"></div>
                <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
             </div>
            <p>Еще нет аккаунта? <a href="{% url 'users:register' %}">Зарегистрироваться</a></p>
        </small>
    </form>
</div>
{% endblock %}

drfsite/users/templates/users/password_reset_complete.html
{% extends 'users/password_reset_form.html' %}

{% block title %}
    Пароль изменен!
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Пароль изменен</h1>
        <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
            <a href="{% url 'users:login' %}">входа в систему</a>.</p>
    </div>
{% endblock %}

drfsite/users/templates/users/password_reset_confirm.html
{% extends 'users/password_reset_form.html' %}

{% block title %}
    Новый пароль
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Новый пароль</h1>
        <form method="post" id="newPasswordForm">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <div class="form-group">
                    <label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>
                    {{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                </div>
            {% endfor %}
            <button type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

drfsite/users/templates/users/password_reset_done.html
{% extends 'users/password_reset_form.html' %}

{% block title %}
    Сброс пароля
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Сброс пароля</h1>
        <p>Мы отправили вам по электронной почте инструкции по установке пароля,
        если у вас есть учетная запись, указав указанный вами адрес электронной почты {{ user.email }}. Вы должны получить их в ближайшее время.</p>
        <p>Если вы не получаете электронное письмо, пожалуйста, убедитесь, что вы
        указали адрес, который указывали при регистрации, и проверьте папку со спамом.</p>
    </div>
{% endblock %}

drfsite/users/templates/users/password_reset_email.html
Здравствуйте!

Кто-то запросил сброс пароля для учетной записи с электронной почтой {{ user.email }}. Если это были вы, пожалуйста, нажмите на ссылку ниже, чтобы установить новый пароль:

[Сбросить пароль]( {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %})

Если вы не запрашивали сброс пароля, просто проигнорируйте это сообщение. Ваш пароль останется без изменений.

С уважением,

Команда поддержки

drfsite/users/templates/users/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/reset_password.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %} Восстановление пароля {% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="container">
        <h1>Восстановление пароля</h1>
        <form method="post">
            {% csrf_token %}
            {% if form.email.errors %}
                <div class="form-error">{{ form.email.errors }}</div>
            {% endif %}
            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">Введите ваш Email</label>
                <input type="email" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" placeholder="Email" required>
            </div>
            <p><button type="submit">Сбросить по E-mail</button></p>
        </form>
    </div>
{% endblock %}
</body>
</html>

drfsite/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="profile-container">
            <div class="profile-header">
                {% if user.photo %}
                    <div class="profile-photo">
                        <img src="{{user.photo.url}}" alt="Фото профиля">
                    </div>
                {% else %}
                    <div class="profile-photo">
                        <img src="{% static 'users/img/empty_profile.jpeg' %}" alt="Фото профиля">
                    </div>
                {% endif %}
                <div class="profile-header-info">
                    <h2>{{ user.username }}</h2>
                    {% if user.first_name %}
                        <p><b>Имя:</b> {{ user.first_name }}</p>
                    {% endif %}
                    {% if user.last_name %}
                        <p><b>Фамилия:</b> {{ user.last_name }}</p>
                    {% endif %}
                    {% if user.date_birth %}
                        <p><b>Дата рождения:</b> {{ user.date_birth }}</p>
                    {% endif %}
                    <p><b>EMAIL:</b> {{ user.email }}</p>
                </div>
            </div>
            <div class="profile-actions">
                {% if user.id == request.user.id %}
                    <a class="profile-action-btn" href="{% url 'users:update_profile' %}">Редактировать профиль</a>
                    <a class="profile-action-btn" href="{% url 'users:password_reset' %}">Сменить пароль</a>
                    <a class="profile-action-btn" href="{% url 'users:logout' %}">Выйти из аккаунта</a>
                {% endif %}
            </div>
            <div class="profile-actions">
                {% if user.id == request.user.id %}
                    <a class="profile-action-btn" href="{% url 'core:create_post' %}">Создать проект</a>
                {% endif %}
            </div>
        </div>
    {% endif %}

{% endblock %}

drfsite/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/register.css' %}">
{% endblock %}

{% block toppanel %}
{% endblock %}

{% block content %}
<div class="login-form">
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        <input type="hidden" name="next" value="{{ next }}" />
        <small class="form-group">
            <p>Создавая учетную запись, вы соглашаетесь с нашим
                <a href="#" style="color:dodgerblue">Условия и конфиденциальность</a>.
            </p>
         </small>
        <div class="form-group">
            <button type="submit">Зарегистрироваться</button>
        </div>
        <small class="form-group">
            <p>Уже зарегистрированы? <a href="{% url 'users:login' %}">Войти</a></p>
        </small>
    </form>
</div>
{% endblock %}

drfsite/users/templates/users/update_profile.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/update_profile.css' %}">
{% endblock %}

{% block content %}
    <h1>Обновить профиль</h1>
    <div class="profile-update-container">
        <div class="profile-photo">
            {% if user.photo %}
                <img src="{{user.photo.url}}" alt="Фото профиля">
            {% else %}
                <img src="{% static 'users/img/empty_profile.jpeg' %}" alt="Фото профиля">
            {% endif %}
        </div>
        <form method="post" enctype="multipart/form-data" class="profile-form">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <p><button type="submit">Сохранить изменения</button></p>
        </form>
    </div>
{% endblock %}